# Generated by Django 5.2.6 on 2025-09-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('drink', 'drink'), ('sobremesa', 'Sobremesa')], default='comida', max_length=20),
        ),
    ]
